# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppress_event maximize, match:class .*

# Fix some dragging issues with XWayland
#windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 0, match:fullscreen 0, match:pin 0

# Floating steam friend list
windowrule = float on, match:class ^(steam)$
windowrule = tile on, match:class ^(steam)$, match:title ^(Steam)$

# Floating games
windowrule = float on, match:class ^(steam_app_.*)$, match:initial_title ^(..+)$

# Floating user programs
windowrule = float on, match:class ^(net\.davidotek\.pupgui2)$
windowrule = float on, match:class ^(waypaper)$